FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --no-fund --no-audit

COPY . .

EXPOSE 3000

# --host 0.0.0.0 vincula ao endereço de dentro do container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
